### ISSUE TITLE
Refresh every 3 seconds

### ISSUE THREAD

**Issue by nickyhuyskens** [OliveTin/OliveTin#134] opened 2023-03-24 12:40 UTC
at the moment, I see my screen flicker every 3 seconds which is quite frustrating.
I was looking for a way to configure (or even disable) this but I see that the 3000ms is hardcoded.

Can this become configurable? Or maybe it would be even better to only update the dom when a change is detected

**Comment by jamesread** [comment] 2023-03-24 15:45
@nickyhuyskens , yeah, it would be nice if OliveTin didn't do this, and I've been expirmenting with websocket and HTTP2 over just the last few days so that I can push updates to clients, rather than having to poll for changes. 

The flicker will be caused by the elements being created and deleted on each refresh, but, most modern browsers should not visibly flicker like this. What browser/OS combination are you using that is flickering?

**Comment by nickyhuyskens** [comment] 2023-03-24 15:48
@jamesread i had this on both chrome and safari on 2 different MacBooks

**Comment by jamesread** [comment] 2023-08-25 15:35
@nickyhuyskens An update on this, OliveTin will now try and use a websocket connection for status updates, removing the need to poll. It will fall back to the REST API polling if the websocket is not available. 

It does need to be tested a bit more, but it will be included in the next release.

**Closed by jamesread** 2023-08-25 15:35 UTC
Labels: type: bug
