### ISSUE TITLE
FTP from OliveTin to PC browser

### ISSUE THREAD

**Issue by mangaxx** [OliveTin/OliveTin#147] opened 2023-05-29 12:09 UTC
What about the possibility of showing a button for FTP files from the oliveTin server to the PC where is acting the browser?

something like this

    - title: Download results
      icon: '<img src = "customIcons/dwr.png" />'
      ftpDir: /results/was/
      timeout: 1200

The behaviour should show a window to choose the final directory on which store the files from OliveTin server with the default name equal to the original name of the file

**Comment by jamesread** [comment] 2023-08-09 20:33
Hey, so you want to allow users to upload files via OliveTin, is that it? 

If so, what would be the reason you need this feature?

**Comment by mangaxx** [comment] 2023-09-25 08:34
Hi James
sorry for the delay for the answer
I intend to make available for the user of OliveTin interface a function to download, by sftp, logs or configuration files
Thanks

**Comment by mangaxx** [comment] 2023-09-27 07:32
more deeply, I create an interface to some commands producing results in text files and the users of that interface needs to retrieve those informations.
Probably the best way should be:

actions:
    - title: Elenca le URL definite per ogni Cluster
      icon: '<img src = "customIcons/logo-design-49582.png" />'
      shell: ssh host.sys.it '/usr/local/bin/was/listaURL.sh'
      timeout: 120
      resultDir: /usr/local/bin/was
      resultFile: listaURL.txt
      ftpLocalDir: c:\result\

The user/password to SFTP should be written on the head of the yaml

In this way the result of the command should be downloaded to the local PC

**Comment by jamesread** [comment] 2023-09-27 22:32
Okay, that's not necessarily a bad idea - be able to save logs to a certain directory.

**Comment by jamesread** [comment] 2023-12-22 03:02
This is now a dupe of #174 , so closing.

**Closed by jamesread** 2023-12-22 03:02 UTC
Labels: type: feature-request
