### ISSUE TITLE
 log keeps recurring

### ISSUE THREAD

**Issue by charlieshen7** [OliveTin/OliveTin#192] opened 2023-11-17 05:46 UTC
**Describe the bug**
Once the command is executed, the log will continue to appear repeatedly. It's not because of repeated runs, because the log timestamps are all the same.

**Expected behavior**
The log should only appear once during runtime and can remain displayed after updating the browser.

**Screenshots**
![image](https://github.com/OliveTin/OliveTin/assets/31721151/ab1cab91-6829-4e6e-b256-307dae257098)

**Comment by rwalkerands** [comment] 2023-11-24 04:43
Exactly the same for me; my setup: running under podman.

Browser developer network tools shows a repeating sequence of pairs of GetDashboardComponents/GetLogs requests.

**Comment by rwalkerands** [comment] 2023-11-24 05:12
Partially diagnosed ... and not entirely fixed yet.

In my case, it was at least related to #173.

My setup includes proxying with Apache HTTP Server, and I hadn't configured WebSocket proxying and upgrading.

After getting that to work (I think ...), now a duplicate log entry is added "only" at the rate of once a minute, not every three seconds.

**Comment by jamesread** [comment] 2024-02-23 16:10
I'm sorry about this one, it's because OliveTin now re-adds logs that may already exist.

I just pushed a commit that catches existing logs and ignores duplicates. It'll be in the next version of OliveTin.

**Comment by jamesread** [comment] 2024-02-27 21:05
This was fixed in the 2024.02.27 release. @charlieshen7 @rwalkerands would you be kind enough to validate that the new version fixes this for you?

**Comment by rwalkerands** [comment] 2024-02-28 00:00
I'm unable to use 2024.02.27, as there seems to be a regression since the last version I was using (2023.10.25): the values of `href` and `src` attributes now begin with a slash, so that they're not relative addresses, as I need for my non-top-level installation.
E.g.:
what was:
```
<link rel="stylesheet" type="text/css" href="style.css">
<link rel="shortcut icon" type="image/png" href="OliveTinLogo.png">
...
<script type="module" src="main.js"></script>
```

is now:

```
<link rel="stylesheet" type="text/css" href="/index.f2cfa1c5.css">
<link rel="icon shortcut" type="image/png" href="/OliveTinLogo.cfcd091e.png">
...
<script type="module" src="/index.6565ece3.js"></script>
```

**Comment by jamesread** [comment] 2024-02-28 00:41
Damn, you can never get anything for free! 2027.02.27 introduced asset packing and minification - but it's using absolute URIs rather than relative. Let me file a new issue for that.

**Comment by rwalkerands** [comment] 2024-02-29 02:22
With 2024.02.28 (which works for me), I confirm that log entries are not repeated.

**Comment by jamesread** [comment] 2024-02-29 06:58
@rwalkerands Fantastic news, and I'm sorry for the annoying bug in the first place. 

@charlieshen7 , I'm going to close this now as I'm pretty sure this is patched - but if you see this issue still in the latest release then please reopen this issue. :-)

**Closed** 2024-02-29 06:58 UTC
Labels: type: bug, needs: feedback-from-requestor
