### ISSUE TITLE
Timeout option and kill button are not working

### ISSUE THREAD

**Issue by ioqy** [OliveTin/OliveTin#328] opened 2024-06-01 18:35 UTC
Since the latest version with the live console, the timeout option and kill button aren't working anymore.

When starting the following action it runs all the way to the end and can't be terminated with the kill button.

```yaml
  - title: Test
    shell: ping -c 5 1.1.1.1
    popupOnStart: execution-dialog
    maxConcurrent: 1
    timeout: 1
```

**Comment by jamesread** [comment] 2024-06-01 23:05
Hmm, that's very odd. Would you mind showiyme your last few OliveTin logs when you try clicking the kill button? Anything about the action not being found, etc?

**Comment by ioqy** [comment] 2024-06-02 07:01
This is the log when pressing the kill button (multiple times) while the action runs:

```
INFO Action requested                              actionTitle="Test" tags="[]"
INFO Action parse args - Before                    actionTitle="Test" cmd="ping -c 5 1.1.1.1"
INFO Action parse args - After                     actionTitle="Test" cmd="ping -c 5 1.1.1.1"
INFO Action starting                               actionTitle="Test" timeout="3"
INFO Action finished                               actionTitle="Test" exit="-1" outputLength="477" timedOut="true"
```

**Comment by jamesread** [comment] 2024-06-02 08:23
Hmm, so pressing the kill button isn't showing anything in the logs at all?

**Comment by jamesread** [comment] 2024-06-02 11:44
Heya @ioqy , so I took a quick look at this while making breakfast this morning, and there certainly isn't enough helpful logging to tell you if something is going wrong. I'll add some logging to fix that up. 

I'm out with my family all day today (UK time), but I'll be around this evening to publish a patch and add some tests.

**Comment by ioqy** [comment] 2024-06-02 14:13
Please take your time and don't hurry. It's really not urgent at all. This was just something I noticed.

**Comment by jamesread** [comment] 2024-06-02 21:51
Hey @ioqy , I've just taken a look at this now and I cannot seem to find any bugs yet in the killing or timeouts, so I'm not yet marking this as a "bug" but a "support request". It's quite possible it's a bug, but we need to do some more investigation first :-) 

Your request has prompted me to add logs when an action is killed (and when it cannot be killed), it also prompted me to add an integration test for killing actions (ie, find the action in the UI, try and kill it by pressing the button), and that is working on simple actions so far.

I'm going to make a release today, can you test 2024.06.02 and see what happens that time? (it'll be out in a couple of hours after this comment).

**Comment by ioqy** [comment] 2024-06-04 07:22
```
INFO Action requested                              actionTitle="Test" tags="[]"
INFO Action parse args - Before                    actionTitle="Test" cmd="ping -c 5 1.1.1.1"
INFO Action parse args - After                     actionTitle="Test" cmd="ping -c 5 1.1.1.1"
INFO Action starting                               actionTitle="Test" timeout="3"
DEBU Adding CORS header origin: "http://olivetin"
WARN Killing execution request by tracking ID: 274d7d0d-2c8c-46cb-9746-7854e0e5bc5e
WARN Killing execution request err: os: process already finished
INFO Action finished                               actionTitle="Test" exit="-1" outputLength="477" timedOut="true"
```

**Comment by jamesread** [comment] 2024-06-04 07:39
Heya, so the extra logging is very useful - but it looks like OliveTin is doing what it's supposed go be doing. The command ran 5 pings, but looks like it was killed by the timeout timer (default 3 seconds), and when you try and kill it again, it's already killed.

**Comment by ioqy** [comment] 2024-06-04 10:40
Without timestamps it looks like the kill button worked. But the kill button does nothing and I can see in the live console that the action is still running after I pressed the kill button.

Here are the logs from journalctl with timestamps.

In this I pressed the kill button once right after the action started:
```
Jun 04 12:22:51 OliveTin[2667793]: level="info" msg="Action requested" actionTitle="Test" tags="[]"
Jun 04 12:22:51 OliveTin[2667793]: level="info" msg="Action parse args - Before" actionTitle="Test" cmd="ping -c 5 1.1.1.1"
Jun 04 12:22:51 OliveTin[2667793]: level="info" msg="Action parse args - After" actionTitle="Test" cmd="ping -c 5 1.1.1.1"
Jun 04 12:22:51 OliveTin[2667793]: level="info" msg="Action starting" actionTitle="Test" timeout="3"
Jun 04 12:22:52 OliveTin[2667793]: level="debug" msg="Adding CORS header origin: \"http://olivetin\""
Jun 04 12:22:52 OliveTin[2667793]: level="warning" msg="Killing execution request by tracking ID: 94596b8b-66c8-4266-ae45-471fa3d749d2"
Jun 04 12:22:55 OliveTin[2667793]: level="info" msg="Action finished" actionTitle="Test" exit="-1" outputLength="477" timedOut="true"
```

In this I pressed the kill button multiple times:
```
Jun 04 12:27:07 OliveTin[2667793]: level="info" msg="Action requested" actionTitle="Test" tags="[]"
Jun 04 12:27:07 OliveTin[2667793]: level="info" msg="Action parse args - Before" actionTitle="Test" cmd="ping -c 5 1.1.1.1"
Jun 04 12:27:07 OliveTin[2667793]: level="info" msg="Action parse args - After" actionTitle="Test" cmd="ping -c 5 1.1.1.1"
Jun 04 12:27:07 OliveTin[2667793]: level="info" msg="Action starting" actionTitle="Test" timeout="3"
Jun 04 12:27:08 OliveTin[2667793]: level="debug" msg="Adding CORS header origin: \"http://olivetin\""
Jun 04 12:27:08 OliveTin[2667793]: level="warning" msg="Killing execution request by tracking ID: 92628325-5597-40b5-ada6-49729311bcef"
Jun 04 12:27:08 OliveTin[2667793]: level="debug" msg="Adding CORS header origin: \"http://olivetin\""
Jun 04 12:27:08 OliveTin[2667793]: level="warning" msg="Killing execution request by tracking ID: 92628325-5597-40b5-ada6-49729311bcef"
Jun 04 12:27:08 OliveTin[2667793]: level="warning" msg="Killing execution request err: os: process already finished"
Jun 04 12:27:09 OliveTin[2667793]: level="debug" msg="Adding CORS header origin: \"http://olivetin\""
Jun 04 12:27:09 OliveTin[2667793]: level="warning" msg="Killing execution request by tracking ID: 92628325-5597-40b5-ada6-49729311bcef"
Jun 04 12:27:09 OliveTin[2667793]: level="warning" msg="Killing execution request err: os: process already finished"
Jun 04 12:27:11 OliveTin[2667793]: level="info" msg="Action finished" actionTitle="Test" exit="-1" outputLength="477" timedOut="true"
``` 

As you can see the action performed all 5 pings and took almost 5 seconds even though it has a timeout of 3 seconds and I pressed the kill button.

Looking at the processes on the server while pressing the kill button you can see that the `ping` process keeps running and only the `sh` process is killed.

**Comment by vvrein** [comment] 2024-06-13 08:51
Yup, faced this too. Seems like OliveTin is tracing the whole process tree, but killing only the pid of `sh`. When `sh` got killed - the processes that was started by it were adopted by  `pid 1`, and OliveTin continues tracing them, and execution dialog still showing.

As workaround for this might be an option which signal send to child, (e.g. SIGINT, SIGHUP, ...) and `trap` them in script, since SIGKILL can not be trapped.

```
actions:
  - title: test
    shell: ...
    killSignal: SIGINT
```

Or option to kill whole process tree.

**Comment by vvrein** [comment] 2024-06-13 10:54
Steps to reproduce:

[video](https://github.com/OliveTin/OliveTin/assets/17022100/25ad7625-b55d-4977-a23e-41d9791d4932)


- start test
- kill test (shouldn't succeed)
- close test
- run find sleep (sleep 124444 still running)

config.yaml
```
actions:
  - title: test
    shell: ./test.sh
    popupOnStart: execution-dialog

  - title: find sleep
    shell: ps axu | grep sleep
    popupOnStart: execution-dialog
```

test.sh
```
#!/bin/bash
echo $$
echo sleep
sleep 124444
echo after sleep
```

---

As not so flexible but still workaround exec may be used in config.yaml and for executing the last and main task in script:
config.yaml
```
actions:
  - title: test
    shell: exec ./test.sh
    popupOnStart: execution-dialog
```

test.sh
```
#!/bin/bash
# ...
# some shell wrapper tasks goes here
# ...
n=$((RANDOM % 60))
exec sleep $n
# echo after sleep will never be reached
echo after sleep
```

**Comment by jamesread** [comment] 2024-06-13 11:04
Hey folks, just a comment to say I appreciate the extra detail and patience while I look into this. I was doing some testing the other night and it does seem like sh is being killed, but not the forked processes. I'm not sure why this doesn't reproduce in my dev environment (outside of a container), but I'll write some more tests for this.

**Comment by vvrein** [comment] 2024-06-13 16:44
I found this to be working to kill the whole process tree by button, but still timeout action kills only the main process. 
Please, be careful, I have no experience with go 😀

```diff
diff --git a/internal/executor/executor.go b/internal/executor/executor.go
index a671ce7..b4b52e1 100644
--- a/internal/executor/executor.go
+++ b/internal/executor/executor.go
@@ -21,6 +21,7 @@ import (
        "strings"
        "sync"
        "time"
+       "syscall"
 )

 var (
@@ -359,8 +360,9 @@ func wrapCommandInShell(ctx context.Context, finalParsedCommand string) *exec.Cm
        if runtime.GOOS == "windows" {
                return exec.CommandContext(ctx, "cmd", "/C", finalParsedCommand)
        }
-
-       return exec.CommandContext(ctx, "sh", "-c", finalParsedCommand)
+       e := exec.CommandContext(ctx, "sh", "-c", finalParsedCommand)
+       e.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
+       return e
 }

 func appendErrorToStderr(err error, logEntry *InternalLogEntry) {
diff --git a/internal/grpcapi/grpcApi.go b/internal/grpcapi/grpcApi.go
index 307c2fd..b83495f 100644
--- a/internal/grpcapi/grpcApi.go
+++ b/internal/grpcapi/grpcApi.go
@@ -11,6 +11,7 @@ import (
        "errors"
        "net"
        "sort"
+       "syscall"

        acl "github.com/OliveTin/OliveTin/internal/acl"
        config "github.com/OliveTin/OliveTin/internal/config"
@@ -40,9 +41,9 @@ func (api *oliveTinAPI) KillAction(ctx ctx.Context, req *pb.KillActionRequest) (
        ret.Found = found

        if found {
-               log.Warnf("Killing execution request by tracking ID: %v", req.ExecutionTrackingId)
+               log.Warnf("Killing execution request by tracking ID: %v and pid %v, sending signal %v", req.ExecutionTrackingId, execReq.Process.Pid, syscall.SIGKILL )

-               err := execReq.Process.Kill()
+               err := syscall.Kill(-execReq.Process.Pid, syscall.SIGKILL)

                if err != nil {
                        log.Warnf("Killing execution request err: %v", err)
```

**Comment by ioqy** [comment] 2024-06-14 07:14
Wouldn't it be better to initially send a SIGINT and wait a bit for the process to terminate itself and potentially perform some cleanup, instead of just killing it? Or initially just send a SIGINT and if the user presses the kill button again, ask the user if a SIGKILL should be sent?

**Comment by jamesread** [comment] 2024-06-17 10:40
Thanks both for your patience. 

@vvrein really appreciate your PR (amazing work, I was also going down the same road to test with syscall). @ioqy , really appreciate you continuing to comment too. 

@ioqy , hmm, very interesting question about how we design this. 

I think we have the following possible options (we could pick multiple)

**Option 1.** Change the only "kill" behaviour to a SIGKILL syscall (@vvrein 's PR)
This is the cleanest option, as it "fixes" the currently designed behaviour. However, I wonder and worry about needing to send other types of signals in the future (see the options below).

**Option 2.** Have a "terminate" option (SIGINT / SIGTERM) and "kill" (SIGKILL / SIGQUIT) button. 
- I really don't like this option as it makes the UI messy, and I can imagine in the future they'll be lots of requests for different types of signals, like sending a SIGUSR1 (useful for `dd`). 

**Option 3.** Have a customizable "send signal" option UI - but this is cumbersome as kill/terminate are the most often used signals.

**Option 4.** Sending a SIGINT, waiting for a few seconds, and then sending a SIGTERM if the process is still running. 
- This seems a bit clumsy for OliveTin to implement this logic. There would need to be a customizable timeout option.

**Option 5.**  I wonder if a config option against the command, like this, is the right idea? Like;
```yaml
actions:
  - title: foo
    allowSignals:
      - name: KILL
      - name: SIGUSR1
        title: Send USR1
```

**Comment by ioqy** [comment] 2024-06-17 15:50
At least Option 1 should be implemented to fix the current behavior.

Everything else is a nice-to-have that could also be put on a roadmap for later.

What about a mashup of the other options: A single configurable signal per action that is sent on the first press of the kill-button. On the second press of the kill-button the user gets a question if the process should be terminated immediately. When confirming with "no" nothing is done. When confirming with "yes" the process tree is terminated with SIGKILL.

**Comment by vvrein** [comment] 2024-06-17 18:07
In my opinion, it would be nice to do this way:
- rename the button from "kill" to "stop", as the button's purpose is to stop running task, the way how it will be done - is OliveTin's thing.
- per each action - add two configurables: `onTimeoutSignal`, `onStopSignal` (or something like this) which defaults to `SIGKILL`

Then, those ones who wants "custom signal and custom behavior" can wrap their task with some `bash` and `trap`, and make behavior like "send SIGINT three times, if not succeeded, at fourth attempt - send SIGKILL"

About adding separate buttons with separate actions/signals... It not looks like OliveTin trying to be super full featured interactive UI to make every possible job done. It just runs and stops predefined short-living tasks from nice UI, and I think it does its job very well, and should continue in the same direction :)

**Comment by jamesread** [comment] 2024-07-05 08:10
Hey @vvrein , @ioqy , can you test the latest release, 2024.07.03, and see that we're happy that killing processes at least works "as expected" now on Linux?

**Comment by ioqy** [comment] 2024-07-05 08:13
Yes, the processes now get killed as expected.

**Closed** 2024-07-13 19:52 UTC
Labels: type: support, progress: design

**Comment by vvrein** [comment] 2024-07-21 08:16
It works! Thank you!
