### ISSUE TITLE
Actions page not auto hidden

### ISSUE THREAD

**Issue by alanmilinovic** [OliveTin/OliveTin#447] opened 2024-10-20 02:56 UTC
**Describe the bug**
If all actions are assigned to dashboards and couple of them that are hidden (hidden: true), actions page is still present in the side menu.

**To Reproduce**
1. Assigne all actions to the dashboard.
2. Mark at least one action as hidden by adding hidden attribute with value false.

**Expected behavior**
If all actions are present on the dashboard and some of them are hidden, there is no need to have actions present in the side menu because it is a blank page.

**Comment by alanmilinovic** [comment] 2024-10-20 02:56
Not sure if this is a bug or enhancement though.

**Comment by jamesread** [comment] 2024-11-02 01:23
Hey @alanmilinovic , thanks very much for your patience here, and taking the time to submit this bug.

This was being casued because the code to hide the "actions" navigation item was only being run if the viewer was viewing the root page, not if a section was being selected. I think that's the most likely cause of your issue here.

I've just patched this in https://github.com/OliveTin/OliveTin/pull/469 , and will try to get it into a release for you over the weekend.

**Comment by alanmilinovic** [comment] 2024-11-02 04:59
Great James, thanks!

**Comment by jamesread** [comment] 2024-11-02 23:36
Closing as we spoke on discord and confirmed this is now fixed.

**Closed by jamesread** 2024-11-02 23:36 UTC
Labels: type: bug
