### ISSUE TITLE
"Error getting buttons SyntaxError: Unexpected end of JSON input" in Alpine container

### ISSUE THREAD

**Issue by wy580477** [OliveTin/OliveTin#59] opened 2022-04-30 12:02 UTC
I tried to run OliveTin inside Alpine container behind Caddy reverse-proxy, got this error. All other web services behind caddy work fine.

![image](https://user-images.githubusercontent.com/98247050/166103976-90b99226-d6e7-4792-a6c0-395f1a5eb2db.png)

OliveTin version: OliveTin-2022-04-07-amd64.tar.gz
Container: python:alpine3.15

**config.yaml**
```
listenAddressSingleHTTPFrontend: 0.0.0.0:1337
logLevel: "INFO"
actions:
- title: Run backup script
  shell: /opt/backupScript.sh
  icon: backup  
```

**OliveTin logs**

level="info" msg="OliveTin initializing" commit="2d7157703ce2bc03de547b95b6b6f5e8b382b6ee" date="2022-04-07T16:13:59Z" version="2022-04-07"
level="debug" msg="Value of -configdir flag" value="/mypath"
level="info" msg="Setting log level to info"
level="info" msg="Init complete"
level="info" msg="OliveTin started" configDir="/mypath"
level="info" msg="Starting REST API" address="localhost:1339"
level="info" msg="Installation ID" content="1c4775ab-e9f0-4edc-a271-1005699bf146" from="/mypath/installation-id.txt"
level="info" msg="Starting WebUI server" address="localhost:1340"
level="info" msg="Found the webui directory" dir="/var/www/olivetin/"
level="info" msg="Starting single HTTP frontend" address="0.0.0.0:1337"
level="info" msg="Update check complete" NewVersion="none"

**Screenshot of WebDeveloper console logs**

![image](https://user-images.githubusercontent.com/98247050/166104517-48fe5583-4a36-4775-bb3d-fa7ff894a6fb.png)

**Anything else?**

I'm running behind Caddy reverse-proxy.

**Caddyfile config**
```
# Configure OliveTin
handle {$GLOBAL_PORTAL_PATH}/olivetin* {
        redir {$GLOBAL_PORTAL_PATH}/olivetin {$GLOBAL_PORTAL_PATH}/olivetin/
        uri strip_prefix {$GLOBAL_PORTAL_PATH}/olivetin       
        basicauth {              
                {$GLOBAL_USER} HASH
        }     
        reverse_proxy * localhost:1337
}
```

**Comment by jamesread** [comment] 2022-05-01 08:34
Hey @wy580477 , this is most likely because `/api/` is not accessible from your proxy configuration. I've not got documentation for Caddy yet, so I'm installing a test-case VM to reproduce your issue.

Out of interest, the Alpine container, is that one that you've built yourself, or got from somewhere?

**Comment by jamesread** [comment] 2022-05-01 09:09
@wy580477 , actually your Caddy config looks OK, but if you want to use a different path (like "/olivetin"), then OliveTin needs to know where the API address is. You can easily change it from absolute, to relative by setting this in your config.yaml, and everything should work fine.

````
externalRestAddress: "."
````

Let me know if that works OK for you.

I'm going to make two changes to help this problem coming up again for others;

- Default to using relative API paths (this will come in the next version of OliveTin) https://github.com/OliveTin/OliveTin/commit/b816884e945050b01b534e8b6424e7ab912a3763
- Documentation for Caddy (based on your config, thank you!) https://docs.olivetin.app/caddy-path.html

**Comment by wy580477** [comment] 2022-05-01 10:38
> Out of interest, the Alpine container, is that one that you've built yourself, or got from somewhere?

I'm building myself.

> ```
> externalRestAddress: "."
> ```

After adding this,  everything works fine! Thx for your help. Glad for making a little contribution for your project docs.

**Comment by jamesread** [comment] 2022-05-01 13:16
@wy580477 great, glad that it's working now :-) I'll close this as I think nothing else is needed. However, if you've got any comments, or anyone else has additional related feedback then feel free to re-open.

**Closed** 2022-05-01 13:17 UTC
Labels: type: support, progress: next-release, progress: code-done, needs: docs
